const BD_TRANSLATIONS = {
  en: {
    // NAV
    "nav.menu": "Menu",
    "nav.locations": "Locations",
    "nav.investors": "Investors Circle",
    "nav.about": "About",
    "nav.process": "The Process",
    "nav.guide": "Buyer's Guide",
    "nav.whyus": "Why Us?",
    "nav.contact": "Contact",
    "nav.inquiry": "Private inquiry",

    // HERO
    "hero.sell": "Sell",
    "hero.top10": "Top 10",
    "hero.buy": "Buy",

    // FOUNDERS
    "founders.eyebrow": "The founders",
    "founders.title": "Built by closers.<br>Designed for private clients.",
    "founders.body": "Jennifer and I built B&D Realty after 12 years in the Riviera Maya, seeing the same problem again and again: plenty of agents could show property, but very few could truly read the deal — or stay close enough to the client when it mattered. My background is in portfolio management and high-conversion sales, with a focus on numbers, positioning, negotiation, and execution. Jennifer brings a background in event organization, where discretion, precision, timing, and client experience are non-negotiable.<br><br>Coming from the UK and France, we bring an international standard to a local market we know deeply. But more than anything, we built B&D Realty to be the kind of advisory the market was missing: present, honest, strategic, and fully invested in the outcome.",
    "founders.names": "Benjamin Brasher & Jennifer Duzant",

    // CONSULT STRIP
    "consult.eyebrow": "Buying abroad can be confusing",
    "consult.title": "Let's start with a conversation",
    "consult.btn1": "Free consultation call",
    "consult.btn2": "Buyer's guide to Mexico",

    // INVESTORS
    "investors.title": "Private access. Curated returns.",
    "investors.body": "An exclusive network for investors seeking pre-market opportunities across the Riviera Maya. Off-plan allocations, developer relationships, and a track record that speaks at closing.",
    "investors.btn": "Request access",

    // TOP 10
    "top10.eyebrow": "Riviera Maya · Curated by B&D",
    "top10.title": "The <em>Top 10</em>",
    "top10.body": "No browsing. No noise. We've done the work so you don't have to. Every property on this list has been vetted, visited, and validated by B&D. Due diligence done. You go straight to the best.",
    "top10.cat1": "Beachfront",
    "top10.cat1.desc": "The finest oceanfront properties across Cancun, Playa & Tulum.",
    "top10.cat2": "Luxury Villas",
    "top10.cat2.desc": "Architect-designed residences for those who don't compromise.",
    "top10.cat3": "Investors Circle",
    "top10.cat3.desc": "High-yield assets with strong rental income and capital upside. Private access only.",
    "top10.cat4": "Value",
    "top10.cat4.desc": "Smart buys — underpriced, undervalued, and under the radar.",
    "top10.explore": "Explore",
    "top10.access": "Request access",

    // VILLAS
    "villas.eyebrow": "Curated by B&D · Riviera Maya",
    "villas.title": "Luxury <em>Villas</em>",
    "villas.sub": "Hand-selected. Vetted. Ready to view. The finest private residences across Cancun, Playa del Carmen and Tulum.",
    "villas.inquiry": "Private inquiry",
    "villas.none": "None of these feel right?",
    "villas.more": "We have more. Let's talk.",
    "villas.cta": "Private inquiry",
    "villas.filter.all": "All",

    // INVESTORS PAGE
    "inv.eyebrow": "Private · Off-Market · Riviera Maya",
    "inv.title": "Deals you won't find <em>anywhere else.</em>",
    "inv.sub": "Pre-market opportunities sourced through 12 years of relationships. Shared only with people ready to move.",
    "inv.deals.label": "Recent deals made by the circle",
    "inv.join.eyebrow": "Join the circle",
    "inv.join.title": "Get notified first.",
    "inv.join.sub": "Leave your details and we'll be in touch the moment the right deal appears.",
    "inv.step2.eyebrow": "One more step",
    "inv.step2.title": "Tell us about you.",
    "inv.q.ready": "Ready to move quickly if the right deal arrives?",
    "inv.q.location": "Preferred location — select all that apply",
    "inv.q.goal": "Investment goal",
    "inv.q.describe": "Describe the ideal deal for you",
    "inv.q.describe.placeholder": "Be specific — budget, property type, expected return. The more realistic, the faster we can match you.",
    "inv.btn.access": "Request access",
    "inv.btn.continue": "Continue — Book a call",
    "inv.step3.eyebrow": "Last step",
    "inv.step3.title": "Book a call with Benjamin.",
    "inv.step3.sub": "Pick a time that works — 20 minutes is all we need.",
    "inv.step3.btn": "Book your call →",
    "inv.confidential": "Strictly confidential. We don't share your information.",
    "inv.success.title": "You're on the list.",
    "inv.success.sub": "We'll be in touch when the right opportunity arrives.<br>Benjamin & Jennifer",
    "inv.ready.yes": "Yes — I decide fast",
    "inv.ready.maybe": "I need time to evaluate",
    "inv.ready.no": "Still exploring",
    "inv.goal.cashflow": "Cash flow",
    "inv.goal.gains": "Capital gains",
    "inv.goal.mix": "Mix of both",

    // PROCESS PAGE
    "proc.eyebrow": "How we work",
    "proc.title": "A clear path, from first call to <em>closing.</em>",
    "proc.sub": "No surprises. No pressure. Just a structured process built over 12 years, designed to protect you and get the deal done right.",
    "proc.step1.tag": "First call",
    "proc.step1.title": "We talk. Really talk.",
    "proc.step1.desc": "Not emails, not a contact form — a real conversation. We want to understand who you are, what you're looking for, your budget, and what matters most. You get a clear picture of who you're dealing with before anything else happens.",
    "proc.step1.note": "15–30 minutes · No obligation",
    "proc.step2.tag": "Property search",
    "proc.step2.title": "You only see what's worth your time.",
    "proc.step2.desc": "Based on what you've told us, we go to work. There is no MLS in Mexico, the market is fragmented, and not every developer or seller deserves your attention. We filter everything and send you only what genuinely fits, with our straight honest take on each one.",
    "proc.step2.note": "No inbox flooding. Only what's relevant.",
    "proc.step3.tag": "Video call",
    "proc.step3.title": "We go through it together.",
    "proc.step3.desc": "A video call to walk through the shortlist, screen-share properties, dig into the numbers, answer every question. If a partner or spouse is part of the decision, this is the moment to bring them in. By the end of this call, we know exactly what we're going after.",
    "proc.step3.note": "You arrive having already reviewed the selection we've sent.",
    "proc.step4.tag": "Visit preparation",
    "proc.step4.title": "When you come, everything is ready.",
    "proc.step4.desc": "About a week before you arrive, we go over your shortlist one more time, confirm availability, and schedule your viewings in half-days. You land knowing exactly what the plan is.",
    "proc.step4.note": "Can't make it in person? We can move forward remotely too.",
    "proc.step5.tag": "Offer & deposit",
    "proc.step5.title": "When it's right, we move fast.",
    "proc.step5.desc": "Good properties don't wait. When you've found the one, we negotiate on your behalf — price, terms, timeline — and guide you through securing it with a deposit. We've seen too many clients lose their favourite property by waiting a week too long.",
    "proc.step5.note": "We handle the negotiation. You make the final call.",
    "proc.after.eyebrow": "After the deal",
    "proc.after.title": "You don't become a past client. <em>You become family.</em>",
    "proc.after.body1": "The closing isn't the end of our relationship, it's the beginning of a longer one. We check in. We stay involved. Whether it's a question about your rental income, a renovation recommendation, or the right moment to sell, we're still there.",
    "proc.after.body2": "We built B&D Realty to work with people for years, not transactions. The clients we've had the longest are the ones who came back, and brought their friends.",
    "proc.after.item1": "Regular check-ins on your investment",
    "proc.after.item2": "Market updates that affect your property",
    "proc.after.item3": "Trusted referrals — management, renovation, legal",
    "proc.after.item4": "Always a call away, not just when you need to buy again",
    "proc.cta.eyebrow": "Ready when you are",
    "proc.cta.title": "Step one starts with a call.",
    "proc.cta.btn1": "Book a free call",
    "proc.cta.btn2": "Buyer's guide to Mexico",

    // BUYERS GUIDE
    "guide.eyebrow": "Free download",
    "guide.title": "Get the guide.",
    "guide.sub": "Everything you need to know before you buy, legal structure, costs, locations, and what to avoid. Straight talk, no fluff.",
    "guide.btn": "Download the guide →",
    "guide.note": "No spam. No pressure. Just the guide.",
    "guide.success.title": "Your guide is ready.",
    "guide.success.sub": "Click below to download. We'll be in touch if you'd like to talk through any of it.",
    "guide.success.btn": "Download now →",
    "guide.inside.eyebrow": "What's inside",
    "guide.inside.title": "6 chapters. Everything you need.",
    "guide.placeholder.fname": "First name",
    "guide.placeholder.lname": "Last name",
    "guide.placeholder.email": "Email address",
    "guide.placeholder.phone": "Phone / WhatsApp",
    "guide.label.stage": "Where are you in the process?",
    "guide.label.location": "Preferred location",
    "guide.label.budget": "Budget range",
  },

  es: {
    "nav.menu": "Menú",
    "nav.locations": "Ubicaciones",
    "nav.investors": "Círculo de Inversores",
    "nav.about": "Nosotros",
    "nav.process": "El Proceso",
    "nav.guide": "Guía del Comprador",
    "nav.whyus": "¿Por qué nosotros?",
    "nav.contact": "Contacto",
    "nav.inquiry": "Consulta privada",
    "hero.sell": "Vender",
    "hero.top10": "Top 10",
    "hero.buy": "Comprar",
    "founders.eyebrow": "Los fundadores",
    "founders.title": "Construido por expertos.<br>Diseñado para clientes privados.",
    "founders.body": "Jennifer y yo fundamos B&D Realty tras 12 años en la Riviera Maya, viendo el mismo problema una y otra vez: muchos agentes podían mostrar propiedades, pero muy pocos sabían leer el negocio o mantenerse cerca del cliente cuando más importaba. Mi trayectoria es en gestión de carteras y ventas de alto rendimiento. Jennifer aporta su experiencia en organización de eventos, donde la discreción, precisión y experiencia del cliente son imprescindibles.<br><br>Venidos del Reino Unido y Francia, aportamos un estándar internacional a un mercado local que conocemos profundamente.",
    "founders.names": "Benjamin Brasher y Jennifer Duzant",
    "consult.eyebrow": "Comprar en el extranjero puede ser confuso",
    "consult.title": "Empecemos con una conversación",
    "consult.btn1": "Llamada de consulta gratuita",
    "consult.btn2": "Guía del comprador en México",
    "investors.title": "Acceso privado. Retornos curados.",
    "investors.body": "Una red exclusiva para inversores que buscan oportunidades pre-mercado en la Riviera Maya. Asignaciones en plano, relaciones con desarrolladores y un historial que habla por sí mismo.",
    "investors.btn": "Solicitar acceso",
    "top10.eyebrow": "Riviera Maya · Curado por B&D",
    "top10.title": "El <em>Top 10</em>",
    "top10.body": "Sin búsquedas interminables. Sin ruido. Hemos hecho el trabajo por usted. Cada propiedad ha sido verificada, visitada y validada por B&D. Vaya directo a lo mejor.",
    "top10.cat1": "Frente al Mar",
    "top10.cat1.desc": "Las mejores propiedades con vista al océano en Cancún, Playa y Tulum.",
    "top10.cat2": "Villas de Lujo",
    "top10.cat2.desc": "Residencias diseñadas por arquitectos para quienes no negocian la calidad.",
    "top10.cat3": "Círculo de Inversores",
    "top10.cat3.desc": "Activos de alto rendimiento con ingresos de alquiler sólidos. Solo acceso privado.",
    "top10.cat4": "Valor",
    "top10.cat4.desc": "Compras inteligentes, subvaloradas y fuera del radar.",
    "top10.explore": "Explorar",
    "top10.access": "Solicitar acceso",
    "villas.eyebrow": "Curado por B&D · Riviera Maya",
    "villas.title": "Villas de <em>Lujo</em>",
    "villas.sub": "Seleccionadas a mano. Verificadas. Listas para visitar. Las mejores residencias privadas en Cancún, Playa del Carmen y Tulum.",
    "villas.inquiry": "Consulta privada",
    "villas.none": "¿Ninguna le convence?",
    "villas.more": "Tenemos más. Hablemos.",
    "villas.cta": "Consulta privada",
    "villas.filter.all": "Todas",
    "inv.eyebrow": "Privado · Fuera del mercado · Riviera Maya",
    "inv.title": "Negocios que no encontrará <em>en ningún otro lugar.</em>",
    "inv.sub": "Oportunidades pre-mercado obtenidas a través de 12 años de relaciones. Solo para personas listas para actuar.",
    "inv.deals.label": "Negocios recientes del círculo",
    "inv.join.eyebrow": "Únase al círculo",
    "inv.join.title": "Sea el primero en enterarse.",
    "inv.join.sub": "Déjenos sus datos y nos pondremos en contacto cuando aparezca la oportunidad correcta.",
    "inv.step2.eyebrow": "Un paso más",
    "inv.step2.title": "Cuéntenos sobre usted.",
    "inv.q.ready": "¿Listo para moverse rápido si llega la oportunidad correcta?",
    "inv.q.location": "Ubicación preferida",
    "inv.q.goal": "Objetivo de inversión",
    "inv.q.describe": "Describa el negocio ideal para usted",
    "inv.q.describe.placeholder": "Sea específico: presupuesto, tipo de propiedad, retorno esperado.",
    "inv.btn.access": "Solicitar acceso",
    "inv.btn.continue": "Continuar — Reservar llamada",
    "inv.step3.eyebrow": "Último paso",
    "inv.step3.title": "Reserve una llamada con Benjamin.",
    "inv.step3.sub": "Elija un horario que le convenga, 20 minutos es todo lo que necesitamos.",
    "inv.step3.btn": "Reserve su llamada →",
    "inv.confidential": "Estrictamente confidencial. No compartimos su información.",
    "inv.success.title": "Está en la lista.",
    "inv.success.sub": "Nos pondremos en contacto cuando llegue la oportunidad.<br>Benjamin y Jennifer",
    "inv.ready.yes": "Sí, decido rápido",
    "inv.ready.maybe": "Necesito tiempo para evaluar",
    "inv.ready.no": "Aún explorando",
    "inv.goal.cashflow": "Flujo de caja",
    "inv.goal.gains": "Plusvalía",
    "inv.goal.mix": "Combinación de ambos",
    "proc.eyebrow": "Cómo trabajamos",
    "proc.title": "Un camino claro, desde la primera llamada hasta el <em>cierre.</em>",
    "proc.sub": "Sin sorpresas. Sin presión. Un proceso estructurado diseñado para protegerle.",
    "proc.step1.tag": "Primera llamada",
    "proc.step1.title": "Hablamos. De verdad.",
    "proc.step1.desc": "No correos, no formularios, una conversación real. Queremos entender quién es usted, qué busca y qué es lo más importante para usted.",
    "proc.step1.note": "15–30 minutos · Sin compromiso",
    "proc.step2.tag": "Búsqueda de propiedades",
    "proc.step2.title": "Solo verá lo que vale su tiempo.",
    "proc.step2.desc": "Basándonos en lo que nos ha dicho, nos ponemos a trabajar. No existe MLS en México y no todos los desarrolladores merecen su atención. Filtramos todo y le enviamos solo lo que realmente encaja.",
    "proc.step2.note": "Sin saturar su bandeja. Solo lo relevante.",
    "proc.step3.tag": "Videollamada",
    "proc.step3.title": "Lo revisamos juntos.",
    "proc.step3.desc": "Una videollamada para repasar la lista, compartir pantalla con las propiedades y responder cada pregunta. Al final de esta llamada, sabemos exactamente qué buscamos.",
    "proc.step3.note": "Llega habiendo revisado ya la selección que le hemos enviado.",
    "proc.step4.tag": "Preparación de visita",
    "proc.step4.title": "Cuando llegue, todo está listo.",
    "proc.step4.desc": "Aproximadamente una semana antes de su llegada, repasamos su lista, confirmamos disponibilidad y programamos las visitas en medias jornadas.",
    "proc.step4.note": "¿No puede venir en persona? También podemos avanzar de forma remota.",
    "proc.step5.tag": "Oferta y depósito",
    "proc.step5.title": "Cuando es el momento, actuamos rápido.",
    "proc.step5.desc": "Las buenas propiedades no esperan. Cuando encuentre la indicada, negociamos en su nombre y le guiamos para asegurarla con un depósito.",
    "proc.step5.note": "Nosotros manejamos la negociación. Usted toma la decisión final.",
    "proc.after.eyebrow": "Después del negocio",
    "proc.after.title": "No se convierte en un cliente del pasado. <em>Se convierte en familia.</em>",
    "proc.after.body1": "El cierre no es el fin de nuestra relación, es el comienzo de una más larga. Seguimos en contacto.",
    "proc.after.body2": "Construimos B&D Realty para trabajar con personas durante años, no por transacciones.",
    "proc.after.item1": "Seguimiento regular de su inversión",
    "proc.after.item2": "Actualizaciones del mercado que afectan su propiedad",
    "proc.after.item3": "Referencias de confianza: gestión, renovación, legal",
    "proc.after.item4": "Siempre a una llamada de distancia",
    "proc.cta.eyebrow": "Listos cuando usted lo esté",
    "proc.cta.title": "El primer paso empieza con una llamada.",
    "proc.cta.btn1": "Reservar una llamada gratuita",
    "proc.cta.btn2": "Guía del comprador en México",
    "guide.eyebrow": "Descarga gratuita",
    "guide.title": "Obtenga la guía.",
    "guide.sub": "Todo lo que necesita saber antes de comprar. Lenguaje claro, sin rodeos.",
    "guide.btn": "Descargar la guía →",
    "guide.note": "Sin spam. Sin presión. Solo la guía.",
    "guide.success.title": "Su guía está lista.",
    "guide.success.sub": "Haga clic para descargar.",
    "guide.success.btn": "Descargar ahora →",
    "guide.inside.eyebrow": "Qué contiene",
    "guide.inside.title": "6 capítulos. Todo lo que necesita.",
    "guide.placeholder.fname": "Nombre",
    "guide.placeholder.lname": "Apellido",
    "guide.placeholder.email": "Correo electrónico",
    "guide.placeholder.phone": "Teléfono / WhatsApp",
    "guide.label.stage": "¿En qué etapa se encuentra?",
    "guide.label.location": "Ubicación preferida",
    "guide.label.budget": "Rango de presupuesto",
  },

  fr: {
    "nav.menu": "Menu",
    "nav.locations": "Destinations",
    "nav.investors": "Cercle des Investisseurs",
    "nav.about": "À propos",
    "nav.process": "Notre méthode",
    "nav.guide": "Guide de l'acheteur",
    "nav.whyus": "Pourquoi nous ?",
    "nav.contact": "Contact",
    "nav.inquiry": "Demande privée",
    "hero.sell": "Vendre",
    "hero.top10": "Top 10",
    "hero.buy": "Acheter",
    "founders.eyebrow": "Les fondateurs",
    "founders.title": "Bâti par des experts.<br>Conçu pour une clientèle privée.",
    "founders.body": "Jennifer et moi avons fondé B&D Realty après 12 ans dans la Riviera Maya, en constatant le même problème encore et encore : de nombreux agents pouvaient montrer des biens, mais très peu savaient vraiment lire une transaction. Mon parcours est en gestion de portefeuilles et en vente haute performance. Jennifer apporte son expertise en organisation d'événements, où discrétion, précision et expérience client sont essentielles.<br><br>Originaires du Royaume-Uni et de France, nous apportons un standard international à un marché local que nous connaissons profondément.",
    "founders.names": "Benjamin Brasher & Jennifer Duzant",
    "consult.eyebrow": "Acheter à l'étranger peut sembler complexe",
    "consult.title": "Commençons par une conversation",
    "consult.btn1": "Appel de consultation gratuit",
    "consult.btn2": "Guide de l'acheteur au Mexique",
    "investors.title": "Accès privé. Rendements sélectionnés.",
    "investors.body": "Un réseau exclusif pour les investisseurs à la recherche d'opportunités pré-marché dans la Riviera Maya.",
    "investors.btn": "Demander l'accès",
    "top10.eyebrow": "Riviera Maya · Sélectionné par B&D",
    "top10.title": "Le <em>Top 10</em>",
    "top10.body": "Pas de navigation interminable. Pas de bruit. Nous avons fait le travail à votre place. Chaque bien a été vérifié, visité et validé par B&D. Droit vers le meilleur.",
    "top10.cat1": "Bord de mer",
    "top10.cat1.desc": "Les plus belles propriétés en bord d'océan à Cancún, Playa et Tulum.",
    "top10.cat2": "Villas de luxe",
    "top10.cat2.desc": "Résidences conçues par des architectes pour ceux qui ne font pas de compromis.",
    "top10.cat3": "Cercle des Investisseurs",
    "top10.cat3.desc": "Actifs à haut rendement avec revenus locatifs solides. Accès privé uniquement.",
    "top10.cat4": "Valeur",
    "top10.cat4.desc": "Achats intelligents, sous-évalués et discrets.",
    "top10.explore": "Explorer",
    "top10.access": "Demander l'accès",
    "villas.eyebrow": "Sélectionné par B&D · Riviera Maya",
    "villas.title": "Villas de <em>luxe</em>",
    "villas.sub": "Sélectionnées à la main. Vérifiées. Prêtes à visiter.",
    "villas.inquiry": "Demande privée",
    "villas.none": "Aucune ne vous convient ?",
    "villas.more": "Nous en avons d'autres. Parlons-en.",
    "villas.cta": "Demande privée",
    "villas.filter.all": "Toutes",
    "inv.eyebrow": "Privé · Hors marché · Riviera Maya",
    "inv.title": "Des opportunités introuvables <em>ailleurs.</em>",
    "inv.sub": "Opportunités pré-marché issues de 12 ans de relations. Partagées uniquement avec ceux qui sont prêts à agir.",
    "inv.deals.label": "Transactions récentes du cercle",
    "inv.join.eyebrow": "Rejoignez le cercle",
    "inv.join.title": "Soyez notifié en premier.",
    "inv.join.sub": "Laissez vos coordonnées et nous vous contacterons dès qu'une opportunité se présente.",
    "inv.step2.eyebrow": "Une étape de plus",
    "inv.step2.title": "Parlez-nous de vous.",
    "inv.q.ready": "Prêt à agir rapidement si la bonne opportunité se présente ?",
    "inv.q.location": "Destination préférée",
    "inv.q.goal": "Objectif d'investissement",
    "inv.q.describe": "Décrivez l'opportunité idéale",
    "inv.q.describe.placeholder": "Soyez précis : budget, type de bien, rendement attendu.",
    "inv.btn.access": "Demander l'accès",
    "inv.btn.continue": "Continuer — Réserver un appel",
    "inv.step3.eyebrow": "Dernière étape",
    "inv.step3.title": "Réservez un appel avec Benjamin.",
    "inv.step3.sub": "Choisissez un créneau, 20 minutes suffisent.",
    "inv.step3.btn": "Réserver votre appel →",
    "inv.confidential": "Strictement confidentiel.",
    "inv.success.title": "Vous êtes sur la liste.",
    "inv.success.sub": "Nous vous contacterons dès que la bonne opportunité arrive.",
    "inv.ready.yes": "Oui, je décide vite",
    "inv.ready.maybe": "J'ai besoin de temps",
    "inv.ready.no": "J'explore encore",
    "inv.goal.cashflow": "Revenus locatifs",
    "inv.goal.gains": "Plus-value",
    "inv.goal.mix": "Les deux",
    "proc.eyebrow": "Notre méthode",
    "proc.title": "Un parcours clair, du premier appel jusqu'à la <em>signature.</em>",
    "proc.sub": "Pas de surprises. Pas de pression. Un processus structuré conçu pour vous protéger.",
    "proc.step1.tag": "Premier appel",
    "proc.step1.title": "On se parle. Vraiment.",
    "proc.step1.desc": "Pas d'e-mails, pas de formulaires, une vraie conversation. Nous voulons comprendre qui vous êtes, ce que vous cherchez et ce qui compte le plus pour vous.",
    "proc.step1.note": "15–30 minutes · Sans engagement",
    "proc.step2.tag": "Recherche de biens",
    "proc.step2.title": "Vous ne verrez que ce qui vaut votre temps.",
    "proc.step2.desc": "Sur la base de vos critères, nous nous mettons au travail. Pas de MLS au Mexique, le marché est fragmenté. Nous filtrons tout et ne vous envoyons que ce qui correspond vraiment.",
    "proc.step2.note": "Pas de surcharge. Uniquement ce qui est pertinent.",
    "proc.step3.tag": "Appel vidéo",
    "proc.step3.title": "On le fait ensemble.",
    "proc.step3.desc": "Un appel vidéo pour parcourir la sélection, partager l'écran, analyser les chiffres et répondre à chaque question.",
    "proc.step3.note": "Vous arrivez ayant déjà examiné notre sélection.",
    "proc.step4.tag": "Préparation de la visite",
    "proc.step4.title": "Quand vous arrivez, tout est prêt.",
    "proc.step4.desc": "Environ une semaine avant votre arrivée, nous repassons sur votre sélection, confirmons les disponibilités et planifions les visites.",
    "proc.step4.note": "Impossible de vous déplacer ? On peut aussi avancer à distance.",
    "proc.step5.tag": "Offre et dépôt",
    "proc.step5.title": "Quand c'est le bon, on agit vite.",
    "proc.step5.desc": "Les bonnes propriétés n'attendent pas. Quand vous trouvez la bonne, nous négocions en votre nom et vous guidons pour la sécuriser.",
    "proc.step5.note": "Nous gérons la négociation. Vous prenez la décision finale.",
    "proc.after.eyebrow": "Après la transaction",
    "proc.after.title": "Vous ne devenez pas un ancien client. <em>Vous devenez famille.</em>",
    "proc.after.body1": "La signature n'est pas la fin de notre relation, c'est le début d'une relation plus longue.",
    "proc.after.body2": "Nous avons construit B&D Realty pour travailler avec des personnes sur le long terme.",
    "proc.after.item1": "Suivi régulier de votre investissement",
    "proc.after.item2": "Mises à jour du marché",
    "proc.after.item3": "Références de confiance : gestion, rénovation, juridique",
    "proc.after.item4": "Toujours joignable, pas seulement quand vous voulez acheter",
    "proc.cta.eyebrow": "Prêts quand vous l'êtes",
    "proc.cta.title": "La première étape commence par un appel.",
    "proc.cta.btn1": "Réserver un appel gratuit",
    "proc.cta.btn2": "Guide de l'acheteur au Mexique",
    "guide.eyebrow": "Téléchargement gratuit",
    "guide.title": "Obtenez le guide.",
    "guide.sub": "Tout ce que vous devez savoir avant d'acheter.",
    "guide.btn": "Télécharger le guide →",
    "guide.note": "Pas de spam. Juste le guide.",
    "guide.success.title": "Votre guide est prêt.",
    "guide.success.sub": "Cliquez ci-dessous pour télécharger.",
    "guide.success.btn": "Télécharger →",
    "guide.inside.eyebrow": "Contenu",
    "guide.inside.title": "6 chapitres. Tout ce qu'il faut.",
    "guide.placeholder.fname": "Prénom",
    "guide.placeholder.lname": "Nom",
    "guide.placeholder.email": "Adresse e-mail",
    "guide.placeholder.phone": "Téléphone / WhatsApp",
    "guide.label.stage": "Où en êtes-vous ?",
    "guide.label.location": "Destination préférée",
    "guide.label.budget": "Budget",
  },

  ru: {
    "nav.menu": "Меню",
    "nav.locations": "Локации",
    "nav.investors": "Инвесторский клуб",
    "nav.about": "О нас",
    "nav.process": "Процесс",
    "nav.guide": "Руководство покупателя",
    "nav.whyus": "Почему мы?",
    "nav.contact": "Контакт",
    "nav.inquiry": "Частный запрос",
    "hero.sell": "Продать",
    "hero.top10": "Топ 10",
    "hero.buy": "Купить",
    "founders.eyebrow": "Основатели",
    "founders.title": "Создано профессионалами.<br>Для частных клиентов.",
    "founders.body": "Дженнифер и я основали B&D Realty после 12 лет на Ривьере Майя. Мой опыт — управление портфелями и продажи высокого уровня. Дженнифер привносит опыт в организации мероприятий, где дискретность и точность обязательны.<br><br>Родом из Великобритании и Франции, мы привносим международные стандарты в местный рынок, который хорошо знаем.",
    "founders.names": "Бенджамин Брэшер и Дженнифер Дюзан",
    "consult.eyebrow": "Покупка за рубежом может быть сложной",
    "consult.title": "Начнём с разговора",
    "consult.btn1": "Бесплатная консультация",
    "consult.btn2": "Руководство покупателя в Мексике",
    "investors.title": "Частный доступ. Отборные доходы.",
    "investors.body": "Эксклюзивная сеть для инвесторов, ищущих возможности до выхода на рынок в Ривьере Майя.",
    "investors.btn": "Запросить доступ",
    "top10.eyebrow": "Ривьера Майя · Отобрано B&D",
    "top10.title": "<em>Топ 10</em>",
    "top10.body": "Никаких долгих поисков. Каждый объект проверен, посещён и одобрен B&D. Прямо к лучшему.",
    "top10.cat1": "На берегу океана",
    "top10.cat1.desc": "Лучшие объекты на берегу океана в Канкуне, Плайя и Тулуме.",
    "top10.cat2": "Элитные виллы",
    "top10.cat2.desc": "Резиденции от именитых архитекторов для тех, кто не идёт на компромисс.",
    "top10.cat3": "Инвесторский клуб",
    "top10.cat3.desc": "Высокодоходные объекты с сильным арендным потенциалом. Только для участников.",
    "top10.cat4": "Выгодные предложения",
    "top10.cat4.desc": "Недооценённые объекты вне радара.",
    "top10.explore": "Смотреть",
    "top10.access": "Запросить доступ",
    "villas.eyebrow": "Отобрано B&D · Ривьера Майя",
    "villas.title": "<em>Элитные</em> виллы",
    "villas.sub": "Отобраны вручную. Проверены. Готовы к просмотру.",
    "villas.inquiry": "Частный запрос",
    "villas.none": "Ничего подходящего?",
    "villas.more": "У нас есть ещё. Поговорим.",
    "villas.cta": "Частный запрос",
    "villas.filter.all": "Все",
    "inv.eyebrow": "Частное · Вне рынка · Ривьера Майя",
    "inv.title": "Сделки, которые не найти <em>нигде больше.</em>",
    "inv.sub": "Возможности до выхода на рынок, найденные за 12 лет связей. Только для тех, кто готов действовать.",
    "inv.deals.label": "Последние сделки клуба",
    "inv.join.eyebrow": "Вступить в клуб",
    "inv.join.title": "Узнайте первым.",
    "inv.join.sub": "Оставьте свои данные, и мы свяжемся, когда появится подходящая возможность.",
    "inv.step2.eyebrow": "Ещё один шаг",
    "inv.step2.title": "Расскажите о себе.",
    "inv.q.ready": "Готовы действовать быстро, если появится нужная возможность?",
    "inv.q.location": "Предпочтительная локация",
    "inv.q.goal": "Инвестиционная цель",
    "inv.q.describe": "Опишите идеальную сделку",
    "inv.q.describe.placeholder": "Конкретно: бюджет, тип объекта, ожидаемая доходность.",
    "inv.btn.access": "Запросить доступ",
    "inv.btn.continue": "Продолжить — Записаться на звонок",
    "inv.step3.eyebrow": "Последний шаг",
    "inv.step3.title": "Запишитесь на звонок с Бенджамином.",
    "inv.step3.sub": "Выберите удобное время, 20 минут — всё, что нужно.",
    "inv.step3.btn": "Записаться →",
    "inv.confidential": "Строго конфиденциально.",
    "inv.success.title": "Вы в списке.",
    "inv.success.sub": "Мы свяжемся, когда появится подходящая возможность.",
    "inv.ready.yes": "Да, принимаю решения быстро",
    "inv.ready.maybe": "Нужно время на оценку",
    "inv.ready.no": "Пока изучаю",
    "inv.goal.cashflow": "Денежный поток",
    "inv.goal.gains": "Прирост капитала",
    "inv.goal.mix": "Комбинация",
    "proc.eyebrow": "Как мы работаем",
    "proc.title": "Чёткий путь, от первого звонка до <em>закрытия сделки.</em>",
    "proc.sub": "Никаких сюрпризов. Никакого давления. Структурированный процесс для вашей защиты.",
    "proc.step1.tag": "Первый звонок",
    "proc.step1.title": "Мы разговариваем. По-настоящему.",
    "proc.step1.desc": "Не письма, не формы — живой разговор. Мы хотим понять, кто вы, что ищете и что для вас важно.",
    "proc.step1.note": "15–30 минут · Без обязательств",
    "proc.step2.tag": "Поиск объектов",
    "proc.step2.title": "Только то, что стоит вашего внимания.",
    "proc.step2.desc": "На основе ваших критериев мы приступаем к работе. В Мексике нет MLS, рынок фрагментирован. Мы фильтруем всё и присылаем только то, что реально подходит.",
    "proc.step2.note": "Никаких лишних писем. Только по делу.",
    "proc.step3.tag": "Видеозвонок",
    "proc.step3.title": "Разбираем вместе.",
    "proc.step3.desc": "Видеозвонок для просмотра отобранных объектов, анализа цифр и ответов на все вопросы.",
    "proc.step3.note": "Вы приходите, уже ознакомившись с нашей подборкой.",
    "proc.step4.tag": "Подготовка визита",
    "proc.step4.title": "Когда вы приедете, всё готово.",
    "proc.step4.desc": "За неделю до вашего приезда мы пересматриваем список, подтверждаем доступность и планируем просмотры.",
    "proc.step4.note": "Не можете приехать? Можем работать дистанционно.",
    "proc.step5.tag": "Предложение и депозит",
    "proc.step5.title": "Когда всё сходится, действуем быстро.",
    "proc.step5.desc": "Хорошие объекты не ждут. Когда вы нашли нужный, мы ведём переговоры от вашего имени и помогаем его закрепить.",
    "proc.step5.note": "Мы ведём переговоры. Вы принимаете финальное решение.",
    "proc.after.eyebrow": "После сделки",
    "proc.after.title": "Вы не становитесь бывшим клиентом. <em>Вы становитесь семьёй.</em>",
    "proc.after.body1": "Закрытие сделки — не конец наших отношений, а начало более долгих.",
    "proc.after.body2": "B&D Realty создан для работы с людьми годами, а не по разовым сделкам.",
    "proc.after.item1": "Регулярный мониторинг вашей инвестиции",
    "proc.after.item2": "Обновления рынка, влияющие на ваш объект",
    "proc.after.item3": "Проверенные контакты: управление, ремонт, юридические вопросы",
    "proc.after.item4": "Всегда на связи, не только когда хотите купить снова",
    "proc.cta.eyebrow": "Готовы, когда вы готовы",
    "proc.cta.title": "Первый шаг начинается со звонка.",
    "proc.cta.btn1": "Записаться на бесплатный звонок",
    "proc.cta.btn2": "Руководство покупателя в Мексике",
    "guide.eyebrow": "Бесплатная загрузка",
    "guide.title": "Получите руководство.",
    "guide.sub": "Всё, что нужно знать перед покупкой. Честно и по делу.",
    "guide.btn": "Скачать руководство →",
    "guide.note": "Без спама. Только руководство.",
    "guide.success.title": "Ваше руководство готово.",
    "guide.success.sub": "Нажмите ниже, чтобы скачать.",
    "guide.success.btn": "Скачать →",
    "guide.inside.eyebrow": "Что внутри",
    "guide.inside.title": "6 глав. Всё необходимое.",
    "guide.placeholder.fname": "Имя",
    "guide.placeholder.lname": "Фамилия",
    "guide.placeholder.email": "Email",
    "guide.placeholder.phone": "Телефон / WhatsApp",
    "guide.label.stage": "На каком этапе вы находитесь?",
    "guide.label.location": "Предпочтительная локация",
    "guide.label.budget": "Бюджет",
  },

  de: {
    "nav.menu": "Menü",
    "nav.locations": "Standorte",
    "nav.investors": "Investorenkreis",
    "nav.about": "Über uns",
    "nav.process": "Unser Prozess",
    "nav.guide": "Käufer-Leitfaden",
    "nav.whyus": "Warum wir?",
    "nav.contact": "Kontakt",
    "nav.inquiry": "Private Anfrage",
    "hero.sell": "Verkaufen",
    "hero.top10": "Top 10",
    "hero.buy": "Kaufen",
    "founders.eyebrow": "Die Gründer",
    "founders.title": "Aufgebaut von Experten.<br>Gestaltet für private Kunden.",
    "founders.body": "Jennifer und ich haben B&D Realty nach 12 Jahren an der Riviera Maya gegründet. Mein Hintergrund liegt im Portfoliomanagement und vertriebsintensiven Verkauf. Jennifer bringt ihre Erfahrung in der Eventorganisation ein, wo Diskretion und Präzision unabdingbar sind.<br><br>Aus Großbritannien und Frankreich stammend, bringen wir internationale Standards in einen lokalen Markt, den wir tief kennen.",
    "founders.names": "Benjamin Brasher & Jennifer Duzant",
    "consult.eyebrow": "Im Ausland kaufen kann verwirrend sein",
    "consult.title": "Fangen wir mit einem Gespräch an",
    "consult.btn1": "Kostenlose Beratung",
    "consult.btn2": "Käufer-Leitfaden für Mexiko",
    "investors.title": "Privater Zugang. Gezielte Renditen.",
    "investors.body": "Ein exklusives Netzwerk für Investoren, die Vor-Markt-Möglichkeiten an der Riviera Maya suchen.",
    "investors.btn": "Zugang anfragen",
    "top10.eyebrow": "Riviera Maya · Kuratiert von B&D",
    "top10.title": "Die <em>Top 10</em>",
    "top10.body": "Kein endloses Suchen. Jedes Objekt wurde von B&D geprüft, besichtigt und validiert. Direkt zum Besten.",
    "top10.cat1": "Strandlage",
    "top10.cat1.desc": "Die besten Immobilien am Ozean in Cancún, Playa und Tulum.",
    "top10.cat2": "Luxusvillen",
    "top10.cat2.desc": "Von Architekten entworfene Residenzen für anspruchsvolle Käufer.",
    "top10.cat3": "Investorenkreis",
    "top10.cat3.desc": "Ertragstarke Objekte mit hohem Mietpotenzial. Nur privater Zugang.",
    "top10.cat4": "Wert",
    "top10.cat4.desc": "Clevere Käufe — unterbewertet und außerhalb des Radars.",
    "top10.explore": "Entdecken",
    "top10.access": "Zugang anfragen",
    "villas.eyebrow": "Kuratiert von B&D · Riviera Maya",
    "villas.title": "<em>Luxus</em>villen",
    "villas.sub": "Handverlesen. Geprüft. Besichtigungsbereit.",
    "villas.inquiry": "Private Anfrage",
    "villas.none": "Nichts Passendes dabei?",
    "villas.more": "Wir haben mehr. Sprechen wir.",
    "villas.cta": "Private Anfrage",
    "villas.filter.all": "Alle",
    "inv.eyebrow": "Privat · Off-Market · Riviera Maya",
    "inv.title": "Deals, die Sie <em>nirgendwo sonst finden.</em>",
    "inv.sub": "Vor-Markt-Möglichkeiten aus 12 Jahren Beziehungen. Nur für Entscheidungsfreudige.",
    "inv.deals.label": "Aktuelle Deals des Kreises",
    "inv.join.eyebrow": "Dem Kreis beitreten",
    "inv.join.title": "Als Erster informiert werden.",
    "inv.join.sub": "Hinterlassen Sie Ihre Daten und wir melden uns, sobald die richtige Chance erscheint.",
    "inv.step2.eyebrow": "Noch ein Schritt",
    "inv.step2.title": "Erzählen Sie uns von sich.",
    "inv.q.ready": "Bereit, schnell zu handeln, wenn das richtige Angebot kommt?",
    "inv.q.location": "Bevorzugter Standort",
    "inv.q.goal": "Investitionsziel",
    "inv.q.describe": "Beschreiben Sie den idealen Deal",
    "inv.q.describe.placeholder": "Konkret: Budget, Immobilientyp, erwartete Rendite.",
    "inv.btn.access": "Zugang anfragen",
    "inv.btn.continue": "Weiter — Anruf buchen",
    "inv.step3.eyebrow": "Letzter Schritt",
    "inv.step3.title": "Buchen Sie einen Anruf mit Benjamin.",
    "inv.step3.sub": "Wählen Sie einen Termin, 20 Minuten reichen.",
    "inv.step3.btn": "Anruf buchen →",
    "inv.confidential": "Streng vertraulich.",
    "inv.success.title": "Sie sind auf der Liste.",
    "inv.success.sub": "Wir melden uns, wenn die richtige Möglichkeit kommt.",
    "inv.ready.yes": "Ja, ich entscheide schnell",
    "inv.ready.maybe": "Ich brauche Zeit zur Bewertung",
    "inv.ready.no": "Erkunde noch",
    "inv.goal.cashflow": "Cashflow",
    "inv.goal.gains": "Kapitalzuwachs",
    "inv.goal.mix": "Kombination",
    "proc.eyebrow": "Unser Prozess",
    "proc.title": "Ein klarer Weg, vom ersten Anruf bis zum <em>Abschluss.</em>",
    "proc.sub": "Keine Überraschungen. Kein Druck. Ein strukturierter Prozess zu Ihrem Schutz.",
    "proc.step1.tag": "Erster Anruf",
    "proc.step1.title": "Wir reden. Wirklich.",
    "proc.step1.desc": "Keine E-Mails, keine Formulare — ein echtes Gespräch. Wir möchten verstehen, wer Sie sind, was Sie suchen und was am wichtigsten ist.",
    "proc.step1.note": "15–30 Minuten · Unverbindlich",
    "proc.step2.tag": "Immobiliensuche",
    "proc.step2.title": "Nur was Ihre Zeit wert ist.",
    "proc.step2.desc": "Basierend auf Ihren Kriterien machen wir uns an die Arbeit. In Mexiko gibt es kein MLS, der Markt ist fragmentiert. Wir filtern alles und schicken nur wirklich Passendes.",
    "proc.step2.note": "Kein Posteinfluten. Nur Relevantes.",
    "proc.step3.tag": "Videoanruf",
    "proc.step3.title": "Gemeinsam durchgehen.",
    "proc.step3.desc": "Ein Videoanruf zur Durchsicht der Auswahl, Bildschirmfreigabe, Zahlenanalyse und Beantwortung aller Fragen.",
    "proc.step3.note": "Sie kommen vorbereitet, nachdem Sie unsere Auswahl bereits gesehen haben.",
    "proc.step4.tag": "Besuchsvorbereitung",
    "proc.step4.title": "Wenn Sie kommen, ist alles bereit.",
    "proc.step4.desc": "Etwa eine Woche vor Ihrer Ankunft gehen wir die Liste nochmals durch, bestätigen Verfügbarkeiten und planen Besichtigungen.",
    "proc.step4.note": "Können Sie nicht persönlich? Geht auch aus der Ferne.",
    "proc.step5.tag": "Angebot und Anzahlung",
    "proc.step5.title": "Wenn es passt, handeln wir schnell.",
    "proc.step5.desc": "Gute Immobilien warten nicht. Wenn Sie die richtige gefunden haben, verhandeln wir in Ihrem Namen.",
    "proc.step5.note": "Wir verhandeln. Sie treffen die endgültige Entscheidung.",
    "proc.after.eyebrow": "Nach dem Abschluss",
    "proc.after.title": "Sie werden kein ehemaliger Kunde. <em>Sie werden Familie.</em>",
    "proc.after.body1": "Der Abschluss ist nicht das Ende unserer Beziehung, sondern der Beginn einer längeren.",
    "proc.after.body2": "B&D Realty wurde gegründet, um jahrelang mit Menschen zu arbeiten, nicht für Einzeltransaktionen.",
    "proc.after.item1": "Regelmäßiges Monitoring Ihrer Investition",
    "proc.after.item2": "Markt-Updates zu Ihrer Immobilie",
    "proc.after.item3": "Vertrauenswürdige Empfehlungen: Verwaltung, Renovierung, Recht",
    "proc.after.item4": "Immer erreichbar, nicht nur wenn Sie wieder kaufen möchten",
    "proc.cta.eyebrow": "Bereit, wenn Sie es sind",
    "proc.cta.title": "Schritt eins beginnt mit einem Anruf.",
    "proc.cta.btn1": "Kostenlosen Anruf buchen",
    "proc.cta.btn2": "Käufer-Leitfaden für Mexiko",
    "guide.eyebrow": "Kostenloser Download",
    "guide.title": "Holen Sie sich den Leitfaden.",
    "guide.sub": "Alles, was Sie vor dem Kauf wissen müssen.",
    "guide.btn": "Leitfaden herunterladen →",
    "guide.note": "Kein Spam. Nur der Leitfaden.",
    "guide.success.title": "Ihr Leitfaden ist bereit.",
    "guide.success.sub": "Klicken Sie unten zum Herunterladen.",
    "guide.success.btn": "Jetzt herunterladen →",
    "guide.inside.eyebrow": "Inhalt",
    "guide.inside.title": "6 Kapitel. Alles Nötige.",
    "guide.placeholder.fname": "Vorname",
    "guide.placeholder.lname": "Nachname",
    "guide.placeholder.email": "E-Mail-Adresse",
    "guide.placeholder.phone": "Telefon / WhatsApp",
    "guide.label.stage": "Wo stehen Sie im Prozess?",
    "guide.label.location": "Bevorzugter Standort",
    "guide.label.budget": "Budgetrahmen",
  }
};

// Language switcher engine
function bdSetLang(lang) {
  localStorage.setItem('bd_lang', lang);
  const t = BD_TRANSLATIONS[lang] || BD_TRANSLATIONS['en'];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.getAttribute('data-i18n');
    if (t[key] !== undefined) {
      if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
        el.placeholder = t[key];
      } else {
        el.innerHTML = t[key];
      }
    }
  });
  // Update active button
  document.querySelectorAll('.lang-btn').forEach(btn => {
    btn.classList.toggle('active', btn.getAttribute('data-lang') === lang);
  });
}

function bdInitLang() {
  const saved = localStorage.getItem('bd_lang') || 'en';
  bdSetLang(saved);
}
